"""
Django settings for SoftWareProject project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
import django
from django.utils.encoding import force_str

django.utils.encoding.force_text = force_str

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-57azkb#)t$w3onr7)35%ylsj*mjc8k37q79+4x5h_n!d*0*out"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['bjxy.buaase.cn', 'localhost', '114.116.219.157']

# Application definition

INSTALLED_APPS = [
    "simpleui",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django_extensions',
    "sslserver",
    "myApp",
    'widget_tweaks',  # 项目依赖
    'django_tables2',  # 项目依赖
    'django_filters',  # 项目依赖
]

# 如果自定义了Groups模型，请添加如下配置
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    # 'path.to.your.auth.backend.MyModelBackend',
)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'django.middleware.locale.LocaleMiddleware',
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "SoftWareProject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "SoftWareProject.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'SoftwareProj_db',
        'USER': 'root',  #!!!!!!!!!!!!!!
        'PASSWORD': 'yX3dRItNM/0ouw4+xmnxcHZlWiwOCWIDTGxQokgD3Cuwm7Ofkt1sZIp1jWLHNKFY',  #!!!!!!!!!!!
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME":
        "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME":
        "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME":
        "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME":
        "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

# LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True
USE_L10N = True

USE_TZ = False  #取消时区设置

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_OIRS = [
    os.path.join(BASE_DIR, 'static')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'software_static')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 更改默认语言为中文
LANGUAGE_CODE = 'zh-hans'

LANGUAGES = [
    ('en', 'English'),
    ('zh-hans', '简体中文'),
]

SIMPLEUI_HOME_INFO = False

# 注意url按'/admin/应用名小写/模型名小写/'命名。
SIMPLEUI_CONFIG = {
    # 是否使用系统默认菜单，自定义菜单时建议关闭。
    'system_keep':
    False,

    # 用于菜单排序和过滤, 不填此字段为默认排序和全部显示。空列表[] 为全部不显示.
    'menu_display': ['数据库管理', '举报处理', '权限认证'],

    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时刷新展示菜单内容。
    # 一般建议关闭。
    'dynamic':
    False,
    'menus': [
        {
            'app':
            'auth',
            'name':
            '权限认证',
            'icon':
            'fas fa-user-shield',
            'models': [{
                'name': '用户列表',
                'icon': 'fa fa-user',
                'url': 'auth/user/'
            }, {
                'name': '用户组',
                'icon': 'fa fa-th-list',
                'url': 'auth/group/'
            }]
        },
        {
            'name':
            '举报处理',
            'icon':
            '<i class="fa-duotone fa-calendar-days"></i>',
            'models': [
                {
                    'name': '查看举报信息',
                    'url': '/admin/myApp/reported/',
                    'icon': 'fa fa-tasks'
                },
            ]
        },
        {
            'name':
            '数据库管理',
            'icon':
            'fa fa-th-list',
            'models': [
                {
                    'name': 'User',
                    'url': '/admin/myApp/user/',
                    'icon': 'fa fa-tasks'
                },
                {
                    'name': 'Question',
                    'url': '/admin/myApp/question/',
                    'icon': 'fa fa-tasks'
                },
                {
                    'name': 'Answer',
                    'url': '/admin/myApp/answer/',
                    'icon': 'fa fa-tasks'
                },
                {
                    'name': 'Tag',
                    'url': '/admin/myApp/tag/',
                    'icon': 'fa fa-tasks'
                },
                {
                    'name': 'KeyWord',
                    'url': '/admin/myApp/keyword/',
                    'icon': 'fa fa-tasks'
                },
                {
                    'name': 'UserLike',
                    'url': '/admin/myApp/userlike/',
                    'icon': 'fa fa-tasks'
                },
            ]
        },
    ]
}
