# Generated by Django 4.2 on 2023-04-14 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KeyWord",
            fields=[
                ("KID", models.IntegerField(primary_key=True, serialize=False)),
                ("KeyWorldContent", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("TID", models.IntegerField(primary_key=True, serialize=False)),
                ("TagContent", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("UID", models.IntegerField(primary_key=True, serialize=False)),
                ("OpenID", models.IntegerField()),
                ("UserName", models.CharField(max_length=50)),
                ("Sex", models.IntegerField(max_length=1)),
                ("Image", models.ImageField(upload_to="")),
                ("Grade", models.CharField(max_length=4)),
                ("Profession", models.CharField(max_length=50)),
                ("SelfIntro", models.CharField(max_length=120)),
                ("Tags", models.IntegerField(max_length=50)),
                ("DisplayInfo", models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("QID", models.IntegerField(primary_key=True, serialize=False)),
                ("QueTime", models.DateTimeField()),
                ("Title", models.CharField(max_length=50)),
                ("QueContent", models.TextField()),
                ("AnswersNum", models.IntegerField()),
                ("ClickNum", models.IntegerField()),
                ("Picture", models.ImageField(upload_to="")),
                ("Tags", models.IntegerField(max_length=50)),
                (
                    "UID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myApp.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("AID", models.IntegerField(primary_key=True, serialize=False)),
                ("AnsContent", models.TextField()),
                ("AnsTime", models.DateTimeField()),
                ("LikeNum", models.IntegerField()),
                (
                    "QID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myApp.question"
                    ),
                ),
                (
                    "UID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myApp.user"
                    ),
                ),
            ],
        ),
    ]
