# Generated by Django 4.2 on 2023-04-20 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question", name="Tags", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="user", name="DisplayInfo", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="user", name="OpenID", field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="user", name="Sex", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="user", name="Tags", field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name="Reported",
            fields=[
                ("RID", models.IntegerField(primary_key=True, serialize=False)),
                ("ID", models.IntegerField()),
                ("Type", models.IntegerField()),
                ("RepTime", models.DateTimeField()),
                ("UserName", models.CharField(max_length=50)),
                ("Reason", models.TextField()),
                ("isSolved", models.BooleanField()),
                (
                    "UID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myApp.user"
                    ),
                ),
            ],
        ),
    ]
