# Generated by Django 4.2 on 2023-04-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0002_alter_question_tags_alter_user_displayinfo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="AID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="KID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="question",
            name="QID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="reported",
            name="RID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tag",
            name="TID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="UID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
