# Generated by Django 4.2 on 2023-04-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0003_alter_answer_aid_alter_keyword_kid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question", name="Tags", field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name="user", name="Tags", field=models.BinaryField(),
        ),
    ]
