# Generated by Django 4.2 on 2023-04-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0004_alter_question_tags_alter_user_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question", name="Tags", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="user", name="Tags", field=models.IntegerField(),
        ),
    ]
