# Generated by Django 4.2 on 2023-04-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0005_alter_question_tags_alter_user_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="Sex", field=models.CharField(max_length=2),
        ),
    ]
