# Generated by Django 4.2 on 2023-04-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0006_alter_user_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question", name="Tags", field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="user", name="Tags", field=models.BigIntegerField(),
        ),
    ]
