# Generated by Django 4.2 on 2023-04-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0007_alter_question_tags_alter_user_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="Image", field=models.CharField(max_length=60),
        ),
    ]
