# Generated by Django 4.2 on 2023-04-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0008_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="Picture",
            field=models.CharField(max_length=60),
        ),
    ]
