# Generated by Django 4.2 on 2023-04-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0009_alter_question_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="Picture",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
