# Generated by Django 4.2 on 2023-04-21 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0010_alter_question_picture"),
    ]

    operations = [
        migrations.RemoveField(model_name="reported", name="UserName",),
    ]
