# Generated by Django 4.2 on 2023-04-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0011_remove_reported_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="Image", field=models.CharField(max_length=200),
        ),
    ]
