# Generated by Django 4.2 on 2023-04-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0012_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="Picture",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="user", name="Image", field=models.CharField(max_length=400),
        ),
    ]
