# Generated by Django 4.2 on 2023-04-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0014_mygroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="question", name="LikeNum", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="question",
            name="ClickNum",
            field=models.IntegerField(default=0),
        ),
    ]
