# Generated by Django 4.2 on 2023-04-27 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0015_question_likenum_alter_question_clicknum"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("LikeType", models.IntegerField()),
                (
                    "Answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myApp.answer",
                    ),
                ),
                (
                    "Question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myApp.question",
                    ),
                ),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myApp.user"
                    ),
                ),
            ],
            options={"unique_together": {("User", "Answer"), ("User", "Question")},},
        ),
    ]
