# Generated by Django 4.2 on 2023-04-27 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0016_userlike"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userlike", old_name="Answer", new_name="LikeAnswer",
        ),
        migrations.RenameField(
            model_name="userlike", old_name="Question", new_name="LikeQuestion",
        ),
        migrations.RenameField(
            model_name="userlike", old_name="User", new_name="LikeUser",
        ),
        migrations.AlterUniqueTogether(
            name="userlike",
            unique_together={("LikeUser", "LikeQuestion"), ("LikeUser", "LikeAnswer")},
        ),
    ]
