# Generated by Django 3.2 on 2023-06-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_rename_answer_userlike_likeanswer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('Name', models.AutoField(primary_key=True, serialize=False)),
                ('Value', models.CharField(max_length=50)),
            ],
        ),
    ]
